<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "comments".
 *
 * @property integer $id
 * @property string $text
 * @property integer $comment_from
 * @property integer $comment_to
 * @property integer $created_by
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class Comments extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comments';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text'], 'required'],
            [['comment_from', 'comment_to'], 'integer'],
            [['text'], 'string', 'max' => 10000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'text' => Yii::t('models', 'Text'),
            'comment_from' => Yii::t('models', 'Comment From'),
            'comment_to' => Yii::t('models', 'Comment To'),
            'created_by' => Yii::t('models', 'Created By'),
            'created_at' => Yii::t('models', 'Created At'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\CommentsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\CommentsQuery(get_called_class());
    }


}
