<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "company".
 *
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property string $zip
 * @property integer $status
 * @property string $company_head_name
 * @property string $type
 * @property integer $created_by
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class Company extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'company_head_name', 'type'], 'required'],
            [['status'], 'integer'],
            [['name', 'company_head_name', 'type'], 'string', 'max' => 32],
            [['address','about'], 'string', 'max' => 50],
            [['zip'], 'string', 'max' => 11]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'address' => Yii::t('models', 'Address'),
            'zip' => Yii::t('models', 'Zip'),
            'created_by' => Yii::t('models', 'Created By'),
            'created_at' => Yii::t('models', 'Created At'),
            'status' => Yii::t('models', 'Status'),
            'company_head_name' => Yii::t('models', 'Company Head Name'),
            'type' => Yii::t('models', 'Type'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\CompanyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\CompanyQuery(get_called_class());
    }


}
