<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "company_group".
 *
 * @property integer $id
 * @property integer $group_id
 * @property integer $company_id
 * @property integer $status
 * @property integer $user_id
 * @property integer $created_by
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class CompanyGroup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company_group';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['group_id', 'company_id', 'status', 'user_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'group_id' => Yii::t('models', 'Group ID'),
            'company_id' => Yii::t('models', 'Company ID'),
            'status' => Yii::t('models', 'Status'),
            'created_by' => Yii::t('models', 'Created By'),
            'created_at' => Yii::t('models', 'Created At'),
            'user_id' => Yii::t('models', 'User ID'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\CompanyGroupQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\CompanyGroupQuery(get_called_class());
    }


}
