<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "group_order".
 *
 * @property integer $id
 * @property integer $task_id
 * @property integer $group_id
 * @property integer $status
 * @property string $unique_id
 * @property integer $created_by
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class GroupOrder extends \yii\db\ActiveRecord
{

	public $groupIds;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'group_order';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['groupIds', 'task_id',], 'required'],
            [['task_id', 'group_id', 'status'], 'integer'],
            [['unique_id'], 'string', 'max' => 200]
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'task_id' => Yii::t('models', 'Task ID'),
            'group_id' => Yii::t('models', 'Group ID'),
            'created_by' => Yii::t('models', 'Created By'),
            'created_at' => Yii::t('models', 'Created At'),
            'status' => Yii::t('models', 'Status'),
            'unique_id' => Yii::t('models', 'Unique ID'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\GroupOrderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\GroupOrderQuery(get_called_class());
    }


}
