<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "groups".
 *
 * @property integer $id
 * @property string $title
 * @property integer $status
 * @property integer $created_by
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class Groups extends \yii\db\ActiveRecord
{
	public $company_id;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'groups';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title','company_id'], 'required'],
            [['status'], 'integer'],
            [['title'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'title' => Yii::t('models', 'Title'),
            'created_by' => Yii::t('models', 'Created By'),
            'status' => Yii::t('models', 'Status'),
            'created_at' => Yii::t('models', 'Created At'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\GroupsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\GroupsQuery(get_called_class());
    }


}
