<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "task".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $unique_id
 * @property integer $status
 * @property string $order_type
 * @property string $start_date
 * @property string $end_date
 * @property integer $created_by
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class Task extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'task';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'start_date', 'end_date'], 'required'],
            [['status'], 'integer'],
            [['start_date'], 'safe'],
            [['title', 'unique_id', 'order_type', 'end_date'], 'string', 'max' => 200],
            [['description'], 'string', 'max' => 3000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'title' => Yii::t('models', 'Title'),
            'description' => Yii::t('models', 'Description'),
            'unique_id' => Yii::t('models', 'Unique ID'),
            'created_by' => Yii::t('models', 'Created By'),
            'created_at' => Yii::t('models', 'Created At'),
            'status' => Yii::t('models', 'Status'),
            'order_type' => Yii::t('models', 'Order Type'),
            'start_date' => Yii::t('models', 'Start Date'),
            'end_date' => Yii::t('models', 'End Date'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\TaskQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\TaskQuery(get_called_class());
    }


}
